### ISSUE TITLE
Plugin works even after it's deleted

### ISSUE THREAD

**Issue by PercyCho** [JonathanBerkeley/BetterDiscordPlugins#1]
After using it, I was unable to stop spamming messages in the channel I was in, so I disabled and deleted it, but it kept going. In the end, I had to uninstall BetterDiscord in order to stop it.

**Comment by JonathanBerkeley** [comment]
This is only a development build of the plugin. That is quite bizarre behavior. If I get around to it, I'll investigate that. 
Thanks for the info.

**Comment by JonathanBerkeley** [comment]
> After using it, I was unable to stop spamming messages in the channel I was in, so I disabled and deleted it, but it kept going. In the end, I had to uninstall BetterDiscord in order to stop it.

I discovered the cause of this. The code for this was injected, and unloading the plugin did not uninject the code. The latest version (0.0.7) now solves this by uninjecting the plugin when the plugin is unloaded. Also added toasts which tell you when the plugin is enabled or disabled, as well as some optimizations to make it more stable. 

Pressing right arrow will stop the message output, disabling the plugin will uninject it. Let me know if there is any other issues. Thanks.
